#!/data/data/com.termux/files/usr/bin/bash

# [*] Script: MetaExif
# [*] Description: Extract Metadata from an Image
# [*] Author: JRIC2002
# [*] Date: 02/05/2019

#COLORS
        export black='\033[1;30m'
        export red='\033[1;31m'
        export green='\033[1;32m'
        export yellow='\033[1;33m'
        export blue='\033[1;34m'
        export magenta='\033[1;35m'
        export cyan='\033[1;36m'
        export white='\033[0m'

#BANNER

function banner {
	
	printf "
	    $green __  __      _       $yellow _____      _  __
	    $green|  \/  | ___| |_ __ _$yellow| ____|_  _(_)/ _|
	    $green| |\/| |/ _ \ __/ _' $yellow|  _| \ \/ / | |_
	    $green| |  | |  __/ || (_| $yellow| |___ >  <| |  _|
	    $green|_|  |_|\___|\__\__,_$yellow|_____/_/\_\_|_|  $white v1.0

	      $green.:.:.$blue Script encoded by:$white @JRIC2002 $green.:.:.$white
      $green.:.:.$blue Description:$white Extract Metadata from an Image  $green.:.:.$white
	"

}

#EXTRAER METADATOS

function metadatos {
	
	echo ""
	printf "$cyan File Path:$white"
	read -p " " ruta_archivo

	if [ -e $ruta_archivo  ]; then
		echo ""
		printf "$green[$white*$green]$black Extracting Metadata from the File ....\n$white"
		echo ""
		sleep 3
		exiv2 pr $ruta_archivo
	else
		echo ""
		printf "$red[$white*$red] The File or Directory does Not Exist\n$white"
		echo ""
	fi

}

#FUNCIONES

banner
metadatos
